### ISSUE TITLE
SRTM results odd

### ISSUE THREAD

**Issue by dabreegster** [eldang/elevation_lookups#22]
I can now successfully import SRTM data! But in my initial tests around Anchorage and NYC so far, the results seem to have some problems. The issue might be on my side, still looking into it.

![Screenshot from 2021-03-27 11-34-46](https://user-images.githubusercontent.com/1664407/112730738-728bec80-8ef0-11eb-868f-b329018a4f56.png)
Lower Manhattan is apparently flat, except for this vertical strip with a very bizarre pattern of extreme steepness. These values are 20,000 % incline...

I'm seeing lots of elevation values of -32776m.

I'll check the raw output file to see if I'm messing up the import on my end.

**Comment by dabreegster** [comment]
Input:
[input.txt](https://github.com/eldang/elevation_lookups/files/6216180/input.txt)
Output:
[output.txt](https://github.com/eldang/elevation_lookups/files/6216181/output.txt)

Lot of empty lines in the output; I'm skipping those correctly now. But I also see -32768 show up quite a bit. This is one of the things totally blowing up my contour visualization.

**Comment by dabreegster** [comment]
Wild guess: is this similar to #13 -- SRTM encodes nodata in a certain way?

**Comment by eldang** [comment]
Oh my.  From a quick investigation, you've found a pair of very silly bugs:

1. The -32768 is indeed a nodata value.  The fix for #13 should have dealt with that (it simply treats anything deeper than Challenger Deep as automatically suspect data, rather than gambling on the exact nodata values being consistent between files), except that I didn't properly handle cases in which it's the last point in the line.
2. I broke the SRTM tiles downloader in such a way that when it downloads multiple tiles, they end up all being repeats of the NE-most one.  As it happens, I have SRTM tiles saved for Anchorage from before I broke that, so I get good data for Anchorage: [elevation_anchorage.txt](https://github.com/eldang/elevation_lookups/files/6216570/elevation_anchorage.txt) .  But I'm getting the same problem you see for Manhattan: everything W of -7 4 longitude is null because the wrong TIFF was downloaded, and those wacky slopes are all where the street grid falls off the edge of the world.

Neither of these things should be very hard to fix, but I probably won't get to them before Monday.

**Comment by dabreegster** [comment]
> where the street grid falls off the edge of the world

![world](https://user-images.githubusercontent.com/1664407/112737368-4fc0fe80-8f17-11eb-843e-a675ded3c159.jpg)


(And no rush)

**Comment by eldang** [comment]
The thing giving me the greatest sense of urgency about these two bugs is how embarrassed I am by them....

**Comment by eldang** [comment]
I ended up working today so I can take some time off and get out on the bike tomorrow when it won't be blowing a gale.  The two commits I just made have fixed these bugs.  Manhattan is still remarkably flat, but I think that actually reflects reality.  I still get a few negative elevations from SRTM in it, but they're small numbers that I suspect reflect real source data issues rather than a bug: 
[nyc.txt](https://github.com/eldang/elevation_lookups/files/6218479/nyc.txt)
